# Generated by Django 4.1.3 on 2022-12-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='user_photos', verbose_name='Fotoğraf'),
        ),
    ]
