# Generated by Django 4.1.3 on 2022-12-02 03:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_universe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sci_fi', 'Science Fiction'), ('super_hero', 'Superhero'), ('fairy_tale', 'Fairy Tale'), ('humour', 'Humour')], max_length=500),
        ),
    ]
