# Generated by Django 4.1.3 on 2022-12-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='İsim')),
                ('slogan', models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim')),
                ('detail', models.TextField(max_length=200, verbose_name='Detay')),
                ('cover', models.FileField(blank=True, null=True, upload_to='universe', verbose_name='Fotoğraf')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
