# Generated by Django 4.1.3 on 2022-12-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universe',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='universe', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='universe',
            name='slogan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Slogan'),
        ),
    ]
